import{S as g,i as l}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function d(r,o=1){const s="https://pixabay.com/api",n="45306950-544d7ee3c7cf7db24fb2a5eae",e=new URLSearchParams({key:n,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o});try{const t=await fetch(`${s}/?${e.toString()}`);if(!t.ok)throw new Error(t.status);return await t.json()}catch(t){return console.error("Error:",t),null}}function u(r){const o=document.getElementById("gallery");if(o.innerHTML="",r.length===0){iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=r.map(n=>`
          <a class="gallery-item" href="${n.largeImageURL}">
              <img src="${n.webformatURL}" alt="${n.tags}" />
              <div class="features">
                  <p>Likes: ${n.likes}</p>
                  <p>Views: ${n.views}</p>
                  <p>Comments: ${n.comments}</p>
                  <p>Downloads: ${n.downloads}</p>
              </div>
          </a>
        `).join("");o.innerHTML=s,new g(".gallery a")}function f(){document.getElementById("loader").classList.remove("hidden")}function m(){document.getElementById("loader").classList.add("hidden")}function p(){document.querySelector(".btn").classList.remove("hidden")}function h(){document.querySelector(".btn").classList.add("hidden")}let i="",a=1,y=0;document.querySelector("form").addEventListener("submit",async r=>{if(r.preventDefault(),i=document.getElementById("search-input").value.trim(),!i){l.error({title:"Error",message:"Please enter a search query!"});return}a=1,h(),L(),f();const o=await d(i,a);m(),o&&o.hits.length>0?(y=o.totalHits,u(o.hits),p()):l.error({title:"Error",message:"Something went wrong. Please try again later."})});document.querySelector(".btn").addEventListener("click",async()=>{a+=1,f();const r=await d(i,a);m(),r&&r.hits.length>0&&(u(r.hits),w(),a*15>=y&&(h(),l.info({title:"End",message:"We're sorry, but you've reached the end of search results."})))});function L(){document.querySelector(".gallery").innerHTML=""}function w(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
